services:
  build:
    build: .
    # command: npx tailwindcss -i ./frontend/static/input.css -o ./frontend/static/output.css --watch
    tty: true
    volumes:
      - ./frontend:/build/frontend # tailwind watches files in the host's directory (rather than in the container)
    ports:
      - "8080:8080"